server:
  port: 8080
  servlet:
    path: /springbook
  tomcat:
    uri-encoding: UTF-8

spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
  thymeleaf:
    cache: false
    enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 13994880635
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #配置redis
  redis:
      port: 6379
      host: localhost

  #配置MongoDB
  data:
      mongodb:
        database: 1801
        host: localhost
        port: 27017